### ISSUE TITLE
Disable item drop if player is in creative

### ISSUE THREAD

**Issue by Citarofahrer** [LandOfRails/LandOfSignals#31]
Is there any way to disable Blockdrop if the Player is in Creative?

**Comment by MarkenJaden** [comment]
Not yet but should be easy to add 👍🏼

**Comment by MarkenJaden** [comment]
In which Minecraft version or with which blocks does this happen? Because I can't reproduce this right now.

**Comment by Danielxs01** [comment]
I think this is for the stellwand

**Comment by MarkenJaden** [comment]
Ah I see, alright

**Comment by Danielxs01** [comment]
### ToDo:
Replace
> getWorld().dropItem(onPick(), getPos());

With
> super.onBreak();

- [ ]  Done
