### ISSUE TITLE
Better select signal GUI

### ISSUE THREAD

**Issue by MarkenJaden** [LandOfRails/LandOfSignals#46]

**Comment by DevonFrosch** [comment]
Vorschläge zur Umsetzung:
- Skalierung der Signale: Die GUI-Boxen haben eine feste Größe. Finde max(breite, höhe) des Items und skaliere das Item: höhe = höhe / max(breite, höhe) * (itembox-höhe - einPaarPixelRand), Breite analog, der Renderer macht den Rest
- Sortiere Items nach  Pack, dann nach Name
- Die GUI-Liste kann Scrollen -> ggf. eine Zeile pro Pack?

**Comment by DevonFrosch** [comment]
Quick fix:

`itemStackList.sort((a, b) => a.getDisplayName().compare(b.getDisplayName()));`

Insert before this line:
https://github.com/LandOfRails/LandOfSignals/blob/38b6a812dbbec5fd97bb382a102dff95c1bca405/src/main/java/net/landofrails/landofsignals/gui/GuiSelectSignal.java#L40

This should sort the items by display name, thus making it easier to find stuff by name (as opposed to them being sorted by... key probably?).

If there is an easy way to get the name of the signal pack from the `ItemStack` that would be great (perhaps by looking for it with the item id?), but the line above is way better than the current behaviour.

Can create a pull request if you want, but I don't have the setup to test it at the moment.

**Comment by Danielxs01** [comment]
> Quick fix:
> 
> `itemStackList.sort((a, b) => a.getDisplayName().compare(b.getDisplayName()));`
> 
> Insert before this line:
> 
> https://github.com/LandOfRails/LandOfSignals/blob/38b6a812dbbec5fd97bb382a102dff95c1bca405/src/main/java/net/landofrails/landofsignals/gui/GuiSelectSignal.java#L40
> 
> This should sort the items by display name, thus making it easier to find stuff by name (as opposed to them being sorted by... key probably?).
> 
> If there is an easy way to get the name of the signal pack from the `ItemStack` that would be great (perhaps by looking for it with the item id?), but the line above is way better than the current behaviour.
> 
> Can create a pull request if you want, but I don't have the setup to test it at the moment.

Thanks for you suggestion. Im currently working on a new major version.
As of the next major update, items will be displayed directly in the creative inventory tab, your sorting will be implemented (via UniqueID not Displayname, so it will be sorted and grouped by ContentPack)

**Comment by Danielxs01** [comment]
done
