### ISSUE TITLE
Mod crashes at newest UMC versions

### ISSUE THREAD

**Issue by EVgenyGP** [LandOfRails/LandOfSignals#49]
On the UMC version "UniversalModCore-1.12.2-forge-1.1.3-2ef602" (from January 2022) 0.0.4-HOTFIX1 everything worked fine, but when updating UMC to the version "UniversalModCore-1.12.2-forge-1.1.4-af2e44" the game crashes. Please release the update to UMC 1.1.4

[crash-2022-05-19_08.28.21-client.txt](https://github.com/LandOfRails/LandOfSignals/files/8725284/crash-2022-05-19_08.28.21-client.txt)

**Comment by Danielxs01** [comment]
Did you upgrade to the release version of UMC 1.1.4 or did you use the test-/dev-build version of UMC?

First one should work fine, last one will probably not be implemented by us, as it is a unofficial version of UMC.

**Comment by EVgenyGP** [comment]
Of those that I have listed both UMC beta versions, and of course I understand that they are not from a full-fledged release, nevertheless I do not want to use RTM for signaling, and staying on the ancient version of IR is also not an option. I may be wrong, but maybe you should try adding version 1.1.4 to dependencies?

**Comment by Danielxs01** [comment]
I can try to make a unofficial version of LoS for this, but there will be no official version for this as it is not a released version.

**Comment by EVgenyGP** [comment]
Please try to do it, thank you in advance

**Comment by Danielxs01** [comment]
I switched everything that was changed, I'll test it tomorrow and eventually provide the new LoS version.
(Builds are red because it tries to use the latest release version of UMC)

**Comment by Danielxs01** [comment]
Closed, see Discord #test-builds.
