### ISSUE TITLE
Add support for more redstone states

### ISSUE THREAD

**Issue by EVgenyGP** [LandOfRails/LandOfSignals#50]
in RTM, an analogue of redstone is made, but in fact it is useless in LoS, so you can simply read the signal level of redstone, in any case, the traffic light can have up to 16 states (99% is enough for all traffic lights). At the moment, it is possible to make 3 traffic light states only with the help of two signal boxes connected to one traffic light (is this a bug?).

![image](https://user-images.githubusercontent.com/43926723/169453659-7ac8ed04-152b-47f5-9c55-d63143c92104.png)

![image](https://user-images.githubusercontent.com/43926723/169454324-96c3862e-1262-46c8-8e38-afd91a57191e.png)

**Comment by Danielxs01** [comment]
No, it's not a bug, it's wanted and implemented this way. I will take your suggestion and probably implement it in the next version after 1.0.0 (1.1.0 probably)
