### ISSUE TITLE
New signal box

### ISSUE THREAD

**Issue by EVgenyGP** [LandOfRails/LandOfSignals#51]
At the moment, signal box always looks at south, but I think that it is necessary to add the ability to choose a model for it and the ability to turn it (at an angle, as in IR, for example, if "AnglePlacementSegmentation" = 4, then the min angle is 90/4), including I ask you to add the same system of angles to traffic lights

![image](https://user-images.githubusercontent.com/43926723/169458135-41f8878c-410a-43f7-9d69-95b505166f8d.png)

**Comment by Danielxs01** [comment]
Will be implemented with 1.0.0 (next major release)

**Comment by EVgenyGP** [comment]
Or another option, make the Signal box a cube and make a normal texture for it so that it can be easily hidden underground, and make categories for objects (now traffic lights and poles are in one tab of the subject, it would be good if they were divided into different objects)

**Comment by Danielxs01** [comment]
There will be a division in signals and signs (without different states like signals) in the next major release.

**Comment by Danielxs01** [comment]
Done
