### ISSUE TITLE
UniversalCoreMod error with versions 0.0.5 & 0.0.6

### ISSUE THREAD

**Issue by jordan8396** [LandOfRails/LandOfSignals#56]
Hi, The newest versions (0.0.5 & 0.0.6) seem to be causing an error loading the Universal Mod Core on 1.16.5.
When I load with the previous version (0.0.4-HOTFIX-1) it works fine. every attempt I have the latest UMC installed (1.1.3).

I am using Forge version _1.16.5-forge-36.2.34_, _UniversalModCore-1.16.5-forge-1.1.3_, and _LandOfSignals-1.16.5-forge-0.0.4-HOTFIX-1_ (Works) / _LandOfSignals-1.16.5-forge-0.0.5_ (Crashes) / _LandOfSignals-1.16.5-forge-0.0.6_ (Crashes)

All other mods are unchanged and work fine with version 0.0.4

Error Screen thrown: ![image](https://user-images.githubusercontent.com/70548908/177061351-8872915f-da4f-4fe6-a6c0-38c9acb987ab.png)
Forge Crash log: [crash-2022-07-04_00.20.54-fml.txt](https://github.com/LandOfRails/LandOfSignals/files/9035665/crash-2022-07-04_00.20.54-fml.txt)
Minecraft Log: [latest.log](https://github.com/LandOfRails/LandOfSignals/files/9035666/latest.log)

**Comment by jordan8396** [comment]
I have just tried to load the mods in isolation (without the rest of my other mods) however the same result occurred. So I don't believe it is a clash with any other mods.
I also tried to load them in isolation on the latest forge build (1.16.5-forge-36.2.35), and an older known stable build (1.16.5-forge-36.2.20) but again failed to load on both.

**Comment by Danielxs01** [comment]
Seems to be an issue with the current UMC version, I will redirect the issue and notify of any changes regarding this bug.

**Comment by Danielxs01** [comment]
Fixed with 0.0.7 (released today)
Fixed with 1.0.0 (upcoming release)
